# This script is used by the Travis-CI (continuous integration) testing
# framework to run SimulationCrafts tests with every GitHub push or pull-request.
language: cpp

branches:
  only:
    - master
    - legion-dev
    
# Enable Trusty (Ubuntu 14.04 LTS) Beta
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

#env:
  # Each line is a separate build in the build matrix. A build in the build
  # matrix is defined by the environment variables defined on the line, which
  # should be space-delimited. For example,
  # - ABC=ON DEF=OFF GHI=ON
  
matrix:
 exclude:
   - os: osx
     compiler: gcc

before_install:
  # Install bats
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:duggan/bats -y && sudo apt-get update -qq && sudo apt-get install -qq bats; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install bats coreutils; fi

notifications:
  irc:
    channels:
      - "irc.gamers-irc.org#simulationcraft"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    on_success: never # default: always

install:
  # Build SimulationCraft
  - cd engine
  - make -j2
  - cd ..

script:
  # Test SimulationCraft.
  - cd tests
  - ./run.sh enemies.bats
  - ./run.sh classes.bats
  
  # Valgrind
  # - valgrind ../engine/simc Raid_T18M.simc iterations=4
