# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    varProject: vs/simc_vs2015.vcxproj
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    varProject: vs/simc_vs2017.vcxproj
    
# fetch repository as zip archive
shallow_clone: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: WebEngine-NoNetworking


# Custom build Configuration, i.e. Debug, Release, etc.
build_script:
  - MSBuild.exe %varProject% /maxcpucount

test_script:
  ## pass
    
after_test:
  ## pass
